### ISSUE TITLE
VizAlerts Error: HTTPError generating trusted ticket: 

### ISSUE THREAD

**Issue by teja999** [tableau/VizAlerts#44]
Hi Guys,

I have configured vizalerts, however i am getting the below error in an email, can you please help me out. FYI, i have configured Trusted authentication too,any help is appreciated

HTTPError generating trusted ticket: Not Found Request details: Server: mycompany.domain.com.com, Site: , Username: **********, Url: http://mycompany.domain.com/trusted, Postdata: username=**********.

Below is the error, when vizalert.py is executed:

C:\VizAlerts>vizalerts.py
2016-06-16 16:34:26 - [INFO] - LoggerQuickSetup - Logging initialized, writing t
o .\logs\vizalerts.log_2016-06-16.log
2016-06-16 16:34:26 - [DEBUG] - trusted_ticket_test - testing trusted ticket: http://mycompany.domain.com, ********, None
2016-06-16 16:34:26 - [DEBUG] - get_trusted_ticket - Generating trusted ticket.
Request details: Server: mycompany.domain.com, Site: , Username: ********, Url: http://mycompany.domain.com/trusted, Postdata: username=********.
2016-06-16 16:34:27 - [ERROR] - get_trusted_ticket - HTTPError generating truste
d ticket: Not Found  Request details: Server: mycompany.domain.com, Site: ,
 Username: ********, Url: http://mycompany.domain.com/trusted, Pos
tdata: username=********.
2016-06-16 16:34:27 - [ERROR] - trusted_ticket_test - HTTPError generating trust
ed ticket: Not Found  Request details: Server: mycompany.domain.com, Site:
, Username: ********, Url: http://mycompany.domain.com/trusted, Po
stdata: username=********.
2016-06-16 16:34:27 - [INFO] - send_email - sending email: smptservername,sender-email@domain.com,********@domain.com,None,None,ALER
T: VizAlerts failed to execute properly,None
2016-06-16 16:34:27 - [DEBUG] - send_email - email body: HTTPError generating tr
usted ticket: Not Found  Request details: Server: mycompany.domain.com, Sit
e: , Username: ********, Url: http://mycompany.domain.com/trusted,
 Postdata: username=********.
2016-06-16 16:34:27 - [ERROR] - <module> - An unhandled exception occurred: Trac
eback (most recent call last):
  File "C:\VizAlerts\vizalerts.py", line 1654, in <module>
    main()
  File "C:\VizAlerts\vizalerts.py", line 203, in main
    trusted_ticket_test()
  File "C:\VizAlerts\vizalerts.py", line 365, in trusted_ticket_test
    quit_script(errormessage)
  File "C:\VizAlerts\vizalerts.py", line 895, in quit_script
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "C:\VizAlerts\vizalerts.py", line 1654, in <module>
    main()
  File "C:\VizAlerts\vizalerts.py", line 203, in main
    trusted_ticket_test()
  File "C:\VizAlerts\vizalerts.py", line 365, in trusted_ticket_test
    quit_script(errormessage)
  File "C:\VizAlerts\vizalerts.py", line 895, in quit_script
    sys.exit(1)
SystemExit: 1

**Comment by mytableau** [comment]
none

**Comment by mcoles** [comment]
Hey Teja, please send your questions and problems to http://community.tableau.com/vizalerts . That's where the community can assist with these kinds of problems. If we find a legitimate bug, or hear of a feature request, that's what we'd like to use the GitHub issues for. Thanks!
